---
deployment:
  tasks:
    # 1. Define the target public directory
    - export DEPLOYPATH=/home/epssoc88/public_html

    # 2. Install pnpm once if missing
    - if ! command -v pnpm >/dev/null 2>&1; then npm install -g pnpm; fi

    # 3. Install project dependencies
    - pnpm install

    # 4. Run the build script defined in package.json
    - pnpm build

    # 5. Sync the build output to your public_html
    - /bin/rsync -a dist/ $DEPLOYPATH/

    # 6. Correct permissions on directories (755) and files (644)
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 '{}' \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 '{}' \;
